### ISSUE TITLE
Please port thawab to WebKit2

### ISSUE THREAD

**Issue by jbicha** [ojuba-org/thawab#14]
Please port thawab to the new maintained version of webkitgtk. The maintained version is packaged as webkit2gtk in Debian and Ubuntu and webkitgtk4 in Fedora. Linux distributions will be removing the old library soon.

The old webkitgtk is no longer maintained and suffers from dozens of known CVE vulnerabilities that have been fixed in the new library.

**Comment by aelmahmoudy** [comment]
@moceap Please fix this issue, as it is blocking us from updating Thawab on Debian
-- 
‎أحمد المحمودي (Ahmed El-Mahmoudy)
 Digital design engineer
GPG KeyIDs: 4096R/A7EF5671 2048R/EDDDA1B7
GPG Fingerprints:
 6E2E E4BB 72E2 F417 D066  6ABF 7B30 B496 A7EF 5761
 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7

**Comment by aelmahmoudy** [comment]
@muayyad-alsadi thawab will be removed from Debian because of this issue. See: https://bugs.debian.org/893861

Is this project still active ? Or will it be deprecated in favor of thawab-lite ?

**Comment by muayyad-alsadi** [comment]
thawab-lite is not a replacement for thawab,

the new project is merely a viewer that does not require importing and
indexing the book.

yes, I'll revamp thawab as soon as I get sometime to do so.


‪On Thu, Jun 14, 2018 at 2:35 PM ‫أحمد المحمودي‬‎ <notifications@github.com>
wrote:‬

**Comment by jbicha** [comment]
Hi, I just wanted to let you know that Debian will be entering its [freeze stage](https://release.debian.org/#release-dates) soon in preparation for the next stable release of Debian (10 "Buster" due in the middle of next year). If thawab is not ported to the new webkitgtk version soon, it will be removed from Debian. If this issue is not fixed by the beginning of the year, thawab will not be present in Debian 10.

Similarly, I expect the old webkitgtk to be removed from Ubuntu 19.04 which will be released in April.

**Comment by muayyad-alsadi** [comment]
@moceap  would you take care of this?

**Comment by aelmahmoudy** [comment]
Fixed by accepting pull#15
